config/routes.rb
Rails.application.routes.draw do
  get 'users/profile'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  #   /posts
  resources :posts do
    # /posts/comments
    resources :comments
  end

  get '/u/:id', to: 'users#profile', as: 'user'

  # to make home page available from /home
  #   get 'home', to: 'pages#home'
  #   get 'pages/about'
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'pages#home'
end

app/views/layouts/_alerts.html.erb
<% if notice || alert %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <%= link_to "Steve Blogs", root_path, class: "navbar-brand" %>

        <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "About", about_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Posts", posts_path, class: "nav-link" %>
                </li>
            </ul>
            <ul class="navbar-nav">
                <%= render 'user/session_manager' %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Blog</title>
		<meta name="viewport" content="width=device-width,initial-scale=1" />
		<!--  -->
		<%= csrf_meta_tags %>
		<!--  -->
		<%= csp_meta_tag %>

		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
			rel="stylesheet"
			crossorigin="anonymous"
		/>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
			crossorigin="anonymous"
		></script>

		<!--  -->
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
	</head>

	<body>
    <%= turbo_include_tags %>
		<header>
			<%= render 'layouts/navbar' %>
			<!--  -->
			<%= render 'layouts/alerts' %>
		</header>

		<main class="container"><%= yield %></main>
	</body>
</html>